function wrapperNewtonFinDiff(dim, problema, parameters, type_h) 
    

    e = [2,4,6,8,10,12];
    h = zeros(6,1);
    for i=1:6
        h(i) = 10^(-e(i));
    end

    [fbest1, grad_norm1, iter1, time1, roc1, fail1] = wrapperNewtonFinDiffDim(dim, problema, 1, 10, parameters, type_h, h(1));
    [fbest2, grad_norm2, iter2, time2, roc2, fail2] = wrapperNewtonFinDiffDim(dim, problema, 1, 10, parameters, type_h, h(2));
    [fbest3, grad_norm3, iter3, time3, roc3, fail3] = wrapperNewtonFinDiffDim(dim, problema, 1, 10, parameters, type_h, h(3));
    [fbest4, grad_norm4, iter4, time4, roc4, fail4] = wrapperNewtonFinDiffDim(dim, problema, 1, 10, parameters, type_h, h(4));
    [fbest5, grad_norm5, iter5, time5, roc5, fail5] = wrapperNewtonFinDiffDim(dim, problema, 1, 10, parameters, type_h, h(5));
    [fbest6, grad_norm6, iter6, time6, roc6, fail6] = wrapperNewtonFinDiffDim(dim, problema, 1, 10, parameters, type_h, h(6));

    %Tabella
    disp(["***Risultati per dimensione ", num2str(dim)," e caso ", type_h]);
     T = table([fbest1; fbest2; fbest3; fbest4; fbest5; fbest6], ...
          [grad_norm1; grad_norm2; grad_norm3;grad_norm4; grad_norm5; grad_norm6], ...
          [iter1; iter2; iter3; iter4; iter5; iter6], ...
          [time1; time2; time3; time4;time5;time6], ...
          [roc1; roc2; roc3;roc4;roc5;roc6], ...
          [fail1; fail2; fail3;fail4;fail5;fail6],...
          'VariableNames', {'fbest','grad_norm','n_iter', 'exec_time', 'roc', 'n_fails'}, ...
          'RowNames', {sprintf('h=%d', h(1)), ...
          sprintf('h=%d', h(2)), ...
          sprintf('h=%d', h(3)), ...
          sprintf('h=%d', h(4)) ...
          sprintf('h=%d', h(5)) ...
          sprintf('h=%d', h(6))});  

    display(T);
end
