function wrapperNewtonExact(dimensioni, problema, parameters)    

    [fbest1, grad_norm1, iter1, time1, roc1, fail1] = wrapperNewtonExactDim(dimensioni(1), problema, 1, 10, parameters);
    [fbest2, grad_norm2, iter2, time2, roc2, fail2] = wrapperNewtonExactDim(dimensioni(2), problema, 1, 10, parameters);
    [fbest3, grad_norm3, iter3, time3, roc3, fail3] = wrapperNewtonExactDim(dimensioni(3), problema, 1, 10, parameters);

    %Tabel
     T = table([fbest1; fbest2; fbest3], ...
          [grad_norm1; grad_norm2; grad_norm3], ...
          [iter1; iter2; iter3], ...
          [time1; time2; time3], ...
          [roc1; roc2; roc3], ...
          [fail1; fail2; fail3],...
          'VariableNames', {'fbest','grad_norm','n_iter', 'exec_time', 'roc', 'n_fails'}, ...
          'RowNames', {sprintf('N=%d', dimensioni(1)), ...
          sprintf('N=%d', dimensioni(2)), ...
          sprintf('N=%d', dimensioni(3))});  

    display(T);
end